# Рабочая тетрадь № 2. Практика

Примеры из разделов 1.2 (NumPy), 2.2 (Pandas) и 3.2 (масштабирование). Ячейки запускаются сверху вниз.

## 1. Библиотека NumPy

### Пример 1.2.1

Создать массив 5×2. Вывести все значения массива, значение элемента с индексом (3, 1) и второй столбец. Индексация начинается с нуля.

In [1]:
import numpy as np

x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[:, 1])


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[ 2  4  6  8 10]


### Пример 1.2.2

1. Создать вектор размера 10, заполненный нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.

In [2]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


### Пример 1.2.3

Создать массив 10×10 со случайными значениями, найти минимум, максимум и среднее значение.

In [3]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)


0.015131252439600895 0.9980098191598991 0.5241062803964065


### Пример 1.2.4

Задать матрицу размерности 5×5 и поменять 2 строки местами.

In [4]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print(A)


[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### Пример 1.2.5

Выяснить результат выражений:

`0 * np.nan`, `np.nan == np.nan`, `np.inf > np.nan`, `np.nan - np.nan`, `0.3 == 3 * 0.1`.

In [5]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)


nan
False
False
nan
False


### Пример 1.2.6

Отсортировать массив.

In [6]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))


[1 2 3 4 5 6 7 8]


## 2. Библиотека Pandas

### Пример 2.2.1

Создать Series из списка Python, словаря Python и массива NumPy (для последнего установить буквенные метки).

In [7]:
import pandas as pd

lst = [1, 2, 3, 4, 5]
d = {'a': 1, 'b': 2, 'c': 3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)


0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


### Пример 2.2.2

Дано два Series. Напечатать их первые элементы и все элементы после третьего (во втором фрейме).

In [8]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])


1
5
3    2
4    1
dtype: int64


### Пример 2.2.3

Создайте новый фрейм данных.

In [9]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe


,Имя,Возраст,Водитель
0,Джеки Джексон,38,True
1,Стивен Стивенсон,25,False


### Пример 2.2.4

Загрузить фрейм данных Titanic. В тетради указан адрес `chrisalbon/simulated_datasets`; репозиторий переименован, тот же файл открывается по ссылке ниже.

In [10]:
url = 'https://raw.githubusercontent.com/chrisalbon/sim_data/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)


,Name,PClass,Age,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,29.00,female,1,1
1,"Allison, Miss Helen Loraine",1st,2.00,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
4,"Allison, Master Hudson Trevor",1st,0.92,male,1,0


### Пример 2.2.5

Проанализировать характеристики фрейма: первые строки (`head`), последние строки (`tail`), форма (`shape`) и описательная статистика числовых столбцов (`describe`).

In [11]:
display(dataframe.head(2))
display(dataframe.tail(3))
print(dataframe.shape)
dataframe.describe()


,Name,PClass,Age,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,29.0,female,1,1
1,"Allison, Miss Helen Loraine",1st,2.0,female,0,1


,Name,PClass,Age,Sex,Survived,SexCode
1310,"Zenni, Mr Philip",3rd,22.0,male,0,0
1311,"Lievens, Mr Rene",3rd,24.0,male,0,0
1312,"Zimmerman, Leo",3rd,29.0,male,0,0


(1313, 6)


,Age,Survived,SexCode
count,756.000000,1313.000000,1313.000000
mean,30.397989,0.342727,0.351866
std,14.259049,0.474802,0.477734
min,0.170000,0.000000,0.000000
25%,21.000000,0.000000,0.000000
50%,28.000000,0.000000,0.000000
75%,39.000000,1.000000,1.000000
max,71.000000,1.000000,1.000000


### Пример 2.2.6

Выбрать индивидуальные данные и срез фрейма. Для строк и значений используются `loc` и `iloc`.

In [12]:
dataframe.iloc[1:4]


,Name,PClass,Age,Sex,Survived,SexCode
1,"Allison, Miss Helen Loraine",1st,2.0,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,30.0,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.0,female,0,1


### Пример 2.2.7

Отобрать строки по условию: новый фрейм из пассажиров первого класса.

In [13]:
dataframe[dataframe['PClass'] == '1st'].head(2)


,Name,PClass,Age,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,29.0,female,1,1
1,"Allison, Miss Helen Loraine",1st,2.0,female,0,1


## 3. Работа с числовыми данными

### Пример 3.2.1

Прошкалировать числовой признак в диапазон между двумя значениями (минимакс, от 0 до 1).

In [14]:
from sklearn import preprocessing

feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0, 1))
scaled_feature = minmax_scale.fit_transform(feature)
scaled_feature


array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

### Пример 3.2.2

Преобразовать признак так, чтобы среднее было 0, а стандартное отклонение — 1.

In [15]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(x)
print(standardized)
print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:", standardized.std())


[[-0.76058269]
 [-0.54177196]
 [-0.35009716]
 [-0.32271504]
 [ 1.97516685]]
Среднее: 0
Стандартное отклонение: 1.0


### Пример 3.2.3

Дан фрейм с числовыми столбцами A, B и категориальным столбцом C. Масштабировать числовые столбцы.

In [16]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
dfTest = pd.DataFrame({
    'A': [14.00, 90.20, 90.95, 96.27, 91.21],
    'B': [103.02, 107.26, 110.35, 114.23, 114.68],
    'C': ['big', 'small', 'big', 'small', 'small'],
})
dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest


,A,B,C
0,0.000000,0.000000,big
1,0.926219,0.363636,small
2,0.935335,0.628645,big
3,1.000000,0.961407,small
4,0.938495,1.000000,small
